require_relative "./pieces/bishops"
require_relative "./pieces/king"
require_relative "./pieces/knight"
require_relative "./pieces/null_piece"
require_relative "./pieces/pawn"
require_relative "./pieces/queen"
require_relative "./pieces/rook"
